CREATE DATABASE KBSN
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

-- DAILY_PROG_TABLE
CREATE TABLE `KBSN`.`DAILY_PROG_TABLE` (
  `DAILY_PROG_TABLE_KEY` INT NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(50) NULL,
  `CHANNEL_NAME` VARCHAR(100) NULL,
  `LIVE` VARCHAR(1) NULL,
  `START_TIME` VARCHAR(20) NULL,
  `END_TIME` VARCHAR(20) NULL,
  `SPOT_AVAIL` VARCHAR(1) NULL,
  `ORG_TIME` VARCHAR(20) NULL,
  `PROG_CLASS` VARCHAR(10) NULL,
  `PROG_CODE` VARCHAR(10) NULL,
  `PROG_COUNT` INT NULL,
  `PROG_NAME` VARCHAR(100) NULL,
  `PROG_SUBNAME` VARCHAR(100) NULL,
  `PROG_RATE` INT NULL,
  `PROG_CATEGORY` INT NULL,
  `LICENSE` VARCHAR(45) NULL,
  `DATE` VARCHAR(20) NULL,
  `WHO_CREATED` VARCHAR(45) NULL,
  `WHO_MODIFIED` VARCHAR(45) NULL,
  `WHEN_CREATED` VARCHAR(20) NULL,
  `WHEN_MODIFIED` VARCHAR(20) NULL,
  PRIMARY KEY (`DAILY_PROG_TABLE_KEY`),
  UNIQUE INDEX `DAILY_PROG_TABLE_KEY_UNIQUE` (`DAILY_PROG_TABLE_KEY` ASC),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC));
 
grant all privileges on KBSN.* to kbsn_user@'localhost' identified by 'nobodyknows';
flush privileges;